package(default_visibility = ["//visibility:public"])

load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_proto_library", "cc_test", "cc_library")
load("@rules_proto//proto:defs.bzl", "proto_library")

cc_library(
  name = "debug",
  hdrs = ["debug.h"]
)