load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_proto_library", "cc_test", "cc_library")
load("@rules_proto//proto:defs.bzl", "proto_library")

cc_library(
  name = "framework",
  deps = [
    "@sdl2//:sdl2"
  ]
)