package(default_visibility = ["//visibility:public"])

load("@rules_cc//cc:defs.bzl", "cc_library")
load("@rules_proto//proto:defs.bzl", "proto_library")


cc_library (
  name = "updatable_instance",
  hdrs = ["updatable_instance.h"]
)